language: python
cache: pip
sudo: required
dist: xenial
python:
  - "3.7"
services:
# user: postgres, password: <empty>
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coverage pylint-django pylint-exit
before_script:
script:
  - coverage run manage.py test
  - pylint --rcfile=pylintrc account/ maps/ || pylint-exit $?
after_success:
  - coverage report -m --skip-covered
  - bash <(curl -s https://codecov.io/bash)
